### ISSUE TITLE
加速する機能すごい

### ISSUE THREAD

**Issue by c2cb** [sugaikota/ProjExD#11]
https://github.com/sugaikota/ProjExD/blob/91e06ea145b8a13366cf2f4e26b99869ccaeb42d/ex04/dodge_bomb.py#L149

爆弾が加速する追加機能の実現ができてすごいと思います。
爆弾に触れた際、こうかとんの画像を変化させる機能は自分もまだできていません。よかったらぜひ実現させてあげてください。

**Comment by sugaikota** [comment]
ありがとうございます.
