### ISSUE TITLE
if文の条件式

### ISSUE THREAD

**Issue by Inazuma110** [sugaikota/ProjExD#12]
key_list (pg.key..get_pressed) の要素はTrueかFalseにしかならなそうなので == True は無くて大丈夫だと思いました．
https://github.com/sugaikota/ProjExD/blob/91e06ea145b8a13366cf2f4e26b99869ccaeb42d/ex04/dodge_bomb.py#L11-L20

**Comment by sugaikota** [comment]
修正しました.
