### ISSUE TITLE
四則演算ができてすごい

### ISSUE THREAD

**Issue by c2cb** [sugaikota/ProjExD#3]
https://github.com/sugaikota/ProjExD/blob/57ee01cb860c2f518c24e165aa0cd3e761999b25/ex02/calc.py#L166

四則演算ができていてすごいと思いました。
それだけでなく、0を付加する機能や、小数点なども入れられるので、正直、どうやってやったのか、今のところ見当もつきません。あなたには才能があります。
コメントも丁寧で分かりやすいので、ぜひこのままのびのびとプログラミングをして、地球を美しくしてください。

**Comment by sugaikota** [comment]
コメントありがとうございます。
